# app/schemas/provider.py
# This file defines the Pydantic schemas for payment provider responses.
# It acts as a canonical data structure to decouple the app from gateway-specific formats.

from decimal import Decimal

from pydantic import BaseModel, Field


class ProviderOrderResponse(BaseModel):
    """
    Unified order response returned by any PaymentProvider implementation.
    Standardizes payload structures to decouple service components from provider-specific formats.
    """

    provider_order_id: str = Field(
        ..., description="Unique order ID generated by the payment gateway"
    )
    amount: Decimal = Field(
        ..., description="Authorized order amount in standard currency unit"
    )
    currency: str = Field(
        ..., description="Currency matching the gateway order definition"
    )
    status: str = Field(
        ..., description="Status of the gateway order (e.g. created, active)"
    )
    raw_response: dict = Field(
        ..., description="Full raw JSON payload for audit logging and tracing"
    )
