# alembic/script.py.mako
# Mako template used by Alembic to generate new migration version files.

"""sprint6_escrow_and_pod

Revision ID: 295ef1330340
Revises: 532d692d8c49
Create Date: 2026-07-09 16:38:05.948925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '295ef1330340'
down_revision: Union[str, None] = '532d692d8c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escrow_transaction', sa.Column('released_by', sa.String(length=255), nullable=True))
    op.add_column('pod_event', sa.Column('state', sa.Enum('UPLOADED', 'VERIFIED', 'REJECTED', name='podstate'), nullable=False, server_default='UPLOADED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod_event', 'state')
    op.drop_column('escrow_transaction', 'released_by')
    # ### end Alembic commands ###
