# alembic/script.py.mako
# Mako template used by Alembic to generate new migration version files.

"""add_webhook_states_and_observability

Revision ID: 532d692d8c49
Revises: 3872a2beb943
Create Date: 2026-07-07 18:05:14.810080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '532d692d8c49'
down_revision: Union[str, None] = '3872a2beb943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_event', sa.Column('event_id', sa.String(length=255), nullable=True))
    op.add_column('webhook_event', sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', name='webhookstate'), nullable=False))
    op.add_column('webhook_event', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_webhook_event_event_id'), 'webhook_event', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_event_event_id'), table_name='webhook_event')
    op.drop_column('webhook_event', 'processed_at')
    op.drop_column('webhook_event', 'status')
    op.drop_column('webhook_event', 'event_id')
    # ### end Alembic commands ###
