# alembic/env.py
# This script is run by Alembic to establish database connections and configure migration runs.
# It integrates with our Pydantic Settings to load the database URL dynamically,
# and hooks up our SQLAlchemy Base metadata registry to support autogenerated schema diffs.

from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context

# 1. Import application configuration and DB base metadata
from app.core.config import settings
from app.db.base import Base
# Import all models to ensure they are registered on Base.metadata
# for Alembic autogenerate to detect them.
from app.models.audit import AuditLog  # noqa: F401
from app.models.escrow import EscrowTransaction  # noqa: F401
from app.models.payment import Payment  # noqa: F401
from app.models.pod import PodEvent  # noqa: F401
from app.models.webhook import WebhookEvent  # noqa: F401

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# 2. Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# 3. Set the target metadata so autogenerate can detect schema changes automatically.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.
    This configures the context with just a URL and not an Engine.
    Calls to context.execute() here emit the SQL commands directly to stdout or script file.
    """
    # Fetch the dynamically loaded URL from settings
    url = settings.get_database_url
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.
    In this scenario we create a Database Engine and associate a connection with the context.
    """
    configuration = config.get_section(config.config_ini_section) or {}
    # Inject the database connection URL dynamically from environment
    configuration["sqlalchemy.url"] = settings.get_database_url

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
